# Generated by Django 3.2.5 on 2022-07-05 10:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asdf',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('time_created', models.DateTimeField(default=datetime.datetime(2022, 7, 5, 10, 24, 31, 910589, tzinfo=utc))),
                ('password', models.TextField()),
                ('last_login', models.DateField(default=datetime.datetime(2022, 7, 5, 10, 24, 31, 911534, tzinfo=utc))),
            ],
        ),
    ]
