# Generated by Django 3.2.5 on 2022-07-06 03:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asdf',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2022, 7, 6, 3, 37, 55, 409391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='asdf',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 3, 37, 55, 409391, tzinfo=utc)),
        ),
    ]
