# Generated by Django 3.2.5 on 2022-07-07 08:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0002_auto_20220706_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=20, unique=True, verbose_name='email')),
                ('password', models.TextField()),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('gender', models.CharField(max_length=2, verbose_name='gender')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('idCardNum', models.CharField(max_length=18, verbose_name='idCardNum')),
                ('birthday', models.CharField(max_length=25, verbose_name='birthday')),
                ('profilePath', models.CharField(max_length=255, verbose_name='profilePath')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ElderlyInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('gender', models.CharField(max_length=2, verbose_name='gender')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('idCardNum', models.CharField(max_length=18, verbose_name='idCardNum')),
                ('birthday', models.CharField(max_length=25, verbose_name='birthday')),
                ('checkinDate', models.CharField(max_length=25, verbose_name='checkinDate')),
                ('checkoutDate', models.CharField(max_length=25, verbose_name='checkoutDate')),
                ('imageSetDir', models.CharField(max_length=255, verbose_name='imageSetDir')),
                ('profilePath', models.CharField(max_length=255, verbose_name='profilePath')),
                ('roomNum', models.CharField(max_length=10, verbose_name='roomNum')),
                ('health', models.CharField(max_length=255, verbose_name='health')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('createTime', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 8, 36, 32, 451554, tzinfo=utc))),
                ('updateTime', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('createBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createBy', to='djangoProject.admininfo')),
                ('updateBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateBy', to='djangoProject.admininfo')),
            ],
        ),
        migrations.CreateModel(
            name='EventLevel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('levelName', models.CharField(max_length=20, verbose_name='levelName')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=20, verbose_name='typeName')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FamilyInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wechatId', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('gender', models.CharField(max_length=2, verbose_name='gender')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(max_length=20, unique=True, verbose_name='email')),
                ('createTime', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 8, 36, 32, 452552, tzinfo=utc))),
                ('updateTime', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('createTime', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 8, 36, 32, 452552, tzinfo=utc))),
                ('updateTime', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('ip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('gender', models.CharField(max_length=2, verbose_name='gender')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('idCardNum', models.CharField(max_length=18, verbose_name='idCardNum')),
                ('birthday', models.CharField(max_length=25, verbose_name='birthday')),
                ('hireDate', models.CharField(max_length=25, verbose_name='checkinDate')),
                ('dismissDate', models.CharField(blank=True, max_length=25, verbose_name='checkoutDate')),
                ('imageSetDir', models.CharField(max_length=255, verbose_name='imageSetDir')),
                ('profilePath', models.CharField(max_length=255, verbose_name='profilePath')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('createTime', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 8, 36, 32, 452552, tzinfo=utc))),
                ('updateTime', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='asdf',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 8, 36, 32, 448731, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='asdf',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 8, 36, 32, 448731, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('locationURL', models.CharField(max_length=255)),
                ('beginTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('monitorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoProject.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyElderlyRelationship',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('createTime', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 8, 36, 32, 452552, tzinfo=utc))),
                ('status', models.IntegerField()),
                ('elderlyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.elderlyinfo')),
                ('familyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.familyinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('createTime', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 8, 36, 32, 452552, tzinfo=utc))),
                ('handleTime', models.DateTimeField()),
                ('monitorID', models.CharField(max_length=20)),
                ('images', models.CharField(max_length=2048)),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('isHandled', models.IntegerField()),
                ('status', models.IntegerField()),
                ('relatedID', models.CharField(max_length=500)),
                ('elderly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.elderlyinfo')),
                ('levelId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoProject.eventlevel')),
                ('typeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoProject.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('gender', models.CharField(max_length=2, verbose_name='gender')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('idCardNum', models.CharField(max_length=18, verbose_name='idCardNum')),
                ('birthday', models.CharField(max_length=25, verbose_name='birthday')),
                ('hireDate', models.CharField(max_length=25, verbose_name='checkinDate')),
                ('dismissDate', models.CharField(blank=True, max_length=25, verbose_name='checkoutDate')),
                ('imageSetDir', models.CharField(max_length=255, verbose_name='imageSetDir')),
                ('profilePath', models.CharField(max_length=255, verbose_name='profilePath')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('createTime', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 8, 36, 32, 452552, tzinfo=utc))),
                ('updateTime', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('createBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='djangoProject.admininfo')),
                ('updateBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater', to='djangoProject.admininfo')),
            ],
        ),
        migrations.CreateModel(
            name='ElderlyLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('longitude', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 8, 36, 32, 452552, tzinfo=utc))),
                ('status', models.IntegerField()),
                ('elderlyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.elderlyinfo')),
            ],
        ),
    ]
