# Generated by Django 3.2.5 on 2022-07-07 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0003_auto_20220707_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='email',
            field=models.EmailField(max_length=30, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='asdf',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 16, 14, 27, 52117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='asdf',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 16, 14, 27, 52117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='elderlyinfo',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 16, 14, 27, 53161, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='elderlylocation',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 16, 14, 27, 54153, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 16, 14, 27, 54153, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 16, 14, 27, 55156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='familyelderlyrelationship',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 16, 14, 27, 56153, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='familyinfo',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 16, 14, 27, 56153, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 16, 14, 27, 57143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='volunteerinfo',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 16, 14, 27, 57143, tzinfo=utc)),
        ),
    ]
