# Generated by Django 3.2.5 on 2022-07-09 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0005_auto_20220709_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asdf',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2022, 7, 9, 10, 43, 54, 487908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='asdf',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 10, 43, 54, 487908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='elderlyinfo',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 10, 43, 54, 488905, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='elderlyinfo',
            name='updateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='elderlylocation',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 10, 43, 54, 489905, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 10, 43, 54, 490901, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='updateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 10, 43, 54, 491898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='familyelderlyrelationship',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 10, 43, 54, 493892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='familyinfo',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 10, 43, 54, 492895, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='familyinfo',
            name='updateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 10, 43, 54, 493892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='updateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='volunteerinfo',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 10, 43, 54, 495887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='volunteerinfo',
            name='updateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
